// <auto-generated />

using System;
using CademeucarroApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CademeucarroApi.Migrations
{
    [DbContext(typeof(CadeMeuCarroDataContext))]
    [Migration("20171118141050_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("cademeucarro_api.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsStolen");

                    b.Property<string>("OwnerEmail");

                    b.Property<string>("OwnerPhone");

                    b.Property<string>("Plate");

                    b.Property<DateTime?>("StolenOn");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
